// js/countryData.js
export const countryOptions = {
    expressPaid: [
        "Australia", "Austria", "Belgium", "Bolivia", "Brazil", "Bulgaria",
        "Canada", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia",
        "Finland", "France", "Germany", "Greece", "Hungary", "Ireland",
        "Italy", "Japan", "Latvia", "Lithuania", "Luxembourg", "Malta",
        "Mexico", "Netherlands", "New Zealand", "Norway", "Poland",
        "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden",
        "United Kingdom", "United States", "Vietnam"
    ],
    expressFree: ["Japan", "South Korea"],
    economy: ["United States"],
    standard: [
        "Anguilla", "Antigua and Barbuda", "Aruba", "Australia", "Bahamas",
        "Belize", "Belgium", "Bolivia", "Bosnia and Herzegovina", "Brazil",
        "Brunei", "Bulgaria", "Canada", "Chile", "Colombia", "Costa Rica",
        "Croatia", "Curaçao", "Cyprus", "Denmark", "Dominica", "Dominican Republic",
        "Estonia", "Finland", "France", "French Guiana", "Germany", "Greece",
        "Grenada", "Guadeloupe", "Haiti", "Honduras", "Hong Kong", "Hungary",
        "Ireland", "Italy", "Jamaica", "Japan", "Latvia", "Lithuania", "Luxembourg",
        "Malta", "Malaysia", "Mexico", "Montserrat", "Netherlands", "New Zealand",
        "Nicaragua", "Norway", "Panama", "Paraguay", "Peru", "Philippines",
        "Poland", "Portugal", "Puerto Rico", "Romania", "Saint Kitts and Nevis",
        "Saint Lucia", "Saint Vincent and the Grenadines", "Singapore", "Slovakia",
        "Slovenia", "South Korea", "Spain", "Sweden", "Switzerland",
        "Trinidad and Tobago", "Turks and Caicos Islands", "United Kingdom",
        "United States", "U.S. Virgin Islands", "Venezuela", "Vietnam", "India" // Added India
    ],
    collection: ["Canada", "United States"],
};

export const countryCodeMapping = {
    "Australia": "AU",
    "Austria": "AT",
    "Belgium": "BE",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Bulgaria": "BG",
    "Canada": "CA",
    "Croatia": "HR",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Estonia": "EE",
    "Finland": "FI",
    "France": "FR",
    "Germany": "DE",
    "Greece": "GR",
    "Hungary": "HU",
    "Ireland": "IE",
    "Italy": "IT",
    "Japan": "JP",
    "Latvia": "LV",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malta": "MT",
    "Mexico": "MX",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Norway": "NO",
    "Poland": "PL",
    "Portugal": "PT",
    "Romania": "RO",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Spain": "ES",
    "Sweden": "SE",
    "United Kingdom": "GB",
    "United States": "US",
    "Vietnam": "VN",
    "South Korea": "KR",
    "India": "IN", // Added India
    "Anguilla": "AI",
    "Antigua and Barbuda": "AG",
    "Aruba": "AW",
    "Bahamas": "BS",
    "Belize": "BZ",
    "Bosnia and Herzegovina": "BA",
    "Brunei": "BN",
    "Chile": "CL",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Curaçao": "CW",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "French Guiana": "GF",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Jamaica": "JM",
    "Malaysia": "MY",
    "Montserrat": "MS",
    "Nicaragua": "NI",
    "Panama": "PA",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Puerto Rico": "PR",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Singapore": "SG",
    "Switzerland": "CH",
    "Trinidad and Tobago": "TT",
    "Turks and Caicos Islands": "TC",
    "U.S. Virgin Islands": "VI",
    "Venezuela": "VE",
};
