// js/capitals.js

// Mapping of countries to their capital city's time zones
export const capitalTimeZones = {
    "Australia": "Australia/Sydney",
    "Austria": "Europe/Vienna",
    "Belgium": "Europe/Brussels",
    "Bolivia": "America/La_Paz",
    "Brazil": "America/Sao_Paulo",
    "Bulgaria": "Europe/Sofia",
    "Canada": "America/Toronto",
    "Croatia": "Europe/Zagreb",
    "Cyprus": "Asia/Nicosia",
    "Czech Republic": "Europe/Prague",
    "Denmark": "Europe/Copenhagen",
    "Estonia": "Europe/Tallinn",
    "Finland": "Europe/Helsinki",
    "France": "Europe/Paris",
    "Germany": "Europe/Berlin",
    "Greece": "Europe/Athens",
    "Hungary": "Europe/Budapest",
    "Ireland": "Europe/Dublin",
    "Italy": "Europe/Rome",
    "Japan": "Asia/Tokyo",
    "Latvia": "Europe/Riga",
    "Lithuania": "Europe/Vilnius",
    "Luxembourg": "Europe/Luxembourg",
    "Malta": "Europe/Malta",
    "Mexico": "America/Mexico_City",
    "Netherlands": "Europe/Amsterdam",
    "New Zealand": "Pacific/Auckland",
    "Norway": "Europe/Oslo",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Romania": "Europe/Bucharest",
    "Slovakia": "Europe/Bratislava",
    "Slovenia": "Europe/Ljubljana",
    "Spain": "Europe/Madrid",
    "Sweden": "Europe/Stockholm",
    "United Kingdom": "Europe/London",
    "United States": "America/New_York",
    "Vietnam": "Asia/Ho_Chi_Minh",
    "South Korea": "Asia/Seoul",
    "Anguilla": "America/Anguilla",
    "Antigua and Barbuda": "America/Antigua",
    "Aruba": "America/Aruba",
    "Bahamas": "America/Nassau",
    "Belize": "America/Belize",
    "Bosnia and Herzegovina": "Europe/Sarajevo",
    "Brunei": "Asia/Brunei",
    "Chile": "Chile/Continental",
    "Colombia": "America/Bogota",
    "Costa Rica": "America/Costa_Rica",
    "Curaçao": "America/Curacao",
    "Dominica": "America/Dominica",
    "Dominican Republic": "America/Santo_Domingo",
    "French Guiana": "America/Cayenne",
    "Grenada": "America/Grenada",
    "Guadeloupe": "America/Guadeloupe",
    "Haiti": "America/Port-au-Prince",
    "Honduras": "America/Tegucigalpa",
    "Hong Kong": "Asia/Hong_Kong",
    "Jamaica": "America/Jamaica",
    "Malaysia": "Asia/Kuala_Lumpur",
    "Montserrat": "America/Montserrat",
    "Nicaragua": "America/Managua",
    "Panama": "America/Panama",
    "Paraguay": "America/Asuncion",
    "Peru": "America/Lima",
    "Philippines": "Asia/Manila",
    "Puerto Rico": "America/Puerto_Rico",
    "Saint Kitts and Nevis": "America/St_Kitts",
    "Saint Lucia": "America/St_Lucia",
    "Saint Vincent and the Grenadines": "America/St_Vincent",
    "Singapore": "Asia/Singapore",
    "Switzerland": "Europe/Zurich",
    "Trinidad and Tobago": "America/Port_of_Spain",
    "Turks and Caicos Islands": "America/Grand_Turk",
    "U.S. Virgin Islands": "America/St_Thomas",
    "Venezuela": "America/Caracas",
};
